Exponential:
  centre:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: -inf
      upper: inf
  normalization:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  rate:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 10.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
Gaussian:
  sigma:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 25.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  centre:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: -inf
      upper: inf
  normalization:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
GalPaK:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 1.0
    gaussian_limits:
      lower: -inf
      upper: inf
  z_centre:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 4.0
    width_modifier:
      type: Absolute
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  inclination:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 90.0
    width_modifier:
      type: Absolute
      value: 10.0
    gaussian_limits:
      lower: -inf
      upper: inf
  phi:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 180.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: -inf
      upper: inf
  turnover_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  maximum_velocity:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 600.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  velocity_dispersion:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 10.0
    gaussian_limits:
      lower: 0.0
      upper: inf
kinMS:
  centre_0:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  centre_1:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 1.0
    gaussian_limits:
      lower: -inf
      upper: inf
  z_centre:
    type: Gaussian
    mean: 0.0
    sigma: 0.5
    width_modifier:
      type: Absolute
      value: 0.05
    gaussian_limits:
      lower: -inf
      upper: inf
  intensity:
    type: LogUniform
    lower_limit: 1.0e-06
    upper_limit: 1000000.0
    width_modifier:
      type: Relative
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  effective_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 4.0
    width_modifier:
      type: Absolute
      value: 1.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  inclination:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 90.0
    width_modifier:
      type: Absolute
      value: 10.0
    gaussian_limits:
      lower: -inf
      upper: inf
  phi:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 180.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: -inf
      upper: inf
  turnover_radius:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 1.0
    width_modifier:
      type: Absolute
      value: 0.5
    gaussian_limits:
      lower: 0.0
      upper: inf
  maximum_velocity:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 600.0
    width_modifier:
      type: Absolute
      value: 20.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  velocity_dispersion:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 10.0
    gaussian_limits:
      lower: 0.0
      upper: inf
  vmax_black_hole:
    type: Uniform
    lower_limit: 0.0
    upper_limit: 100.0
    width_modifier:
      type: Absolute
      value: 10.0
    gaussian_limits:
      lower: 0.0
      upper: inf
